// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocioTorcedor.Modules.Payments.Infrastructure.Persistence;

#nullable disable

namespace SocioTorcedor.Modules.Payments.Infrastructure.Migrations.TenantPaymentsDb
{
    [DbContext(typeof(TenantPaymentsDbContext))]
    [Migration("20260412142552_RemoveMemberPaymentWebhookInbox")]
    partial class RemoveMemberPaymentWebhookInbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocioTorcedor.Modules.Payments.Domain.Entities.MemberBillingInvoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<DateTime>("DueAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalInvoiceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("MemberBillingSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("PaidAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("PixCopyPaste")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MemberBillingSubscriptionId");

                    b.ToTable("Payments_MemberBillingInvoices", (string)null);
                });

            modelBuilder.Entity("SocioTorcedor.Modules.Payments.Domain.Entities.MemberBillingSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ExternalCustomerId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ExternalSubscriptionId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("MemberPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MemberProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("NextBillingAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<decimal>("RecurringAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExternalSubscriptionId");

                    b.HasIndex("MemberProfileId");

                    b.ToTable("Payments_MemberBillingSubscriptions", (string)null);
                });

            modelBuilder.Entity("SocioTorcedor.Modules.Payments.Domain.Entities.MemberBillingInvoice", b =>
                {
                    b.HasOne("SocioTorcedor.Modules.Payments.Domain.Entities.MemberBillingSubscription", "Subscription")
                        .WithMany("Invoices")
                        .HasForeignKey("MemberBillingSubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("SocioTorcedor.Modules.Payments.Domain.Entities.MemberBillingSubscription", b =>
                {
                    b.Navigation("Invoices");
                });
#pragma warning restore 612, 618
        }
    }
}
