// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SocioTorcedor.Modules.Backoffice.Infrastructure.Persistence;

#nullable disable

namespace SocioTorcedor.Modules.Backoffice.Infrastructure.Migrations
{
    [DbContext(typeof(BackofficeMasterDbContext))]
    partial class BackofficeMasterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SocioTorcedor.Modules.Backoffice.Domain.Entities.SaaSPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxMembers")
                        .HasColumnType("int");

                    b.Property<decimal>("MonthlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("StripePriceMonthlyId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("StripePriceYearlyId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("YearlyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("SaaSPlans", (string)null);
                });

            modelBuilder.Entity("SocioTorcedor.Modules.Backoffice.Domain.Entities.SaaSPlanFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<Guid>("SaaSPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.HasIndex("SaaSPlanId");

                    b.ToTable("SaaSPlanFeatures", (string)null);
                });

            modelBuilder.Entity("SocioTorcedor.Modules.Backoffice.Domain.Entities.TenantPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BillingCycle")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SaaSPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SaaSPlanId");

                    b.HasIndex("TenantId", "Status")
                        .IsUnique()
                        .HasFilter("[Status] = 0");

                    b.ToTable("TenantPlans", (string)null);
                });

            modelBuilder.Entity("SocioTorcedor.Modules.Backoffice.Domain.Entities.SaaSPlanFeature", b =>
                {
                    b.HasOne("SocioTorcedor.Modules.Backoffice.Domain.Entities.SaaSPlan", "SaaSPlan")
                        .WithMany("Features")
                        .HasForeignKey("SaaSPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SaaSPlan");
                });

            modelBuilder.Entity("SocioTorcedor.Modules.Backoffice.Domain.Entities.TenantPlan", b =>
                {
                    b.HasOne("SocioTorcedor.Modules.Backoffice.Domain.Entities.SaaSPlan", null)
                        .WithMany()
                        .HasForeignKey("SaaSPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("SocioTorcedor.Modules.Backoffice.Domain.Entities.SaaSPlan", b =>
                {
                    b.Navigation("Features");
                });
#pragma warning restore 612, 618
        }
    }
}
